# docker build -t ogarantia/ogre-tensorflow:1.15.5-py3-jupyter -f ./Dockerfile.1.15.5-py3-jupyter .
FROM tensorflow/tensorflow:1.15.5-py3-jupyter

ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && apt install -y ffmpeg libsm6 libxext6 vim nano git

RUN apt-get autoclean && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*