# docker build -t ogrerun/cpu:py3.11 .
# docker run -it --rm ogrerun/cpu:py3.11 bash
FROM python:3.11

RUN python3 -m pip install --upgrade pip

# Set the default Python version
ENV PYTHON_VERSION 3.11
