FROM alpine:3.15.4
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apk update && apk add python3-dev py3-pip build-base libffi-dev bash
RUN pip install jupyterlab
